### ISSUE TITLE
[Bug]ChainMiner3 调试信息和读取cost显示类型错误

### ISSUE THREAD

**Issue by qianxiayouxin** [engsr6982/ChainMiner3#1]
### Describe the bug

1.调试信息未删
2.显示类型报错

### To Reproduce

将json文件中的cost增加数字就会出现该报错，报错显示我填的类型不对，可是我填的确定是数字而不是字符串，报错完其实他是扣费和扣耐久的，但是不会显示“连锁成功”
[config.json](https://github.com/user-attachments/files/15513159/config.json)

### Expected behavior

希望能尽快解决

### Screenshots

![1717155951436](https://github.com/engsr6982/ChainMiner3/assets/96040656/6bfafe5b-ac7b-4b9f-a110-7845a60385e4)

### Platform

Windows 10

### BDS Version

1.20.81

### LeviLamina Version

0.12.2+

### Version

0.1.0

**Comment by engsr6982** [comment]
Fixed https://github.com/engsr6982/ChainMiner3/releases/tag/v0.2.0
