### ISSUE TITLE
[Bug]: 服务器可以运行，后台无报错

### ISSUE THREAD

**Issue by enzo123456fes** [engsr6982/ChainMiner3#2]
### Describe the bug

挖矿，砍树没有连锁效果

### To Reproduce

LeviLamina-0.12.4 with LSE-0.7.12 1.20.80 服务器端没有改config

### Expected behavior

LeviLamina-0.12.4 with LSE-0.7.12 1.20.80 服务器端没有改config

### Platform

win10

### BDS Version

1.20.80

### LeviLamina Version

LeviLamina-0.12.4 with LSE-0.7.12

### Version

0.2.1

**Comment by fjnu025** [comment]
0.13.x，适配1.21.0的一样没有连锁效果，没有任何报错

**Comment by engsr6982** [comment]
> ll3的0.13.x，适配1.21.0的一样没有连锁效果，没有任何报错

试试最新的action
https://github.com/engsr6982/ChainMiner3/actions/runs/9614756771
