### ISSUE TITLE
[Bug]: 使用菜单命令hcm后出现崩溃

### ISSUE THREAD

**Issue by h4chPE-Network** [engsr6982/ChainMiner3#4]
### Describe the bug

此为6月30日一名玩家挖掘/放置方块后出现崩溃错误
[trace_2024-06-30_10-14-09.log](https://github.com/user-attachments/files/16048667/trace_2024-06-30_10-14-09.log)
此为7月1日使用菜单命令后再次出现崩溃错误
并且弹出以下错误说明：
14:01:28.129 ERROR [LeviLamina] Error in command hcm:
14:01:28.139 ERROR [LeviLamina] Raw Seh Exception:
14:01:28.140 ERROR [LeviLamina] [0xC0000005:ntstatus] 0x%p 指令引用了 0x%p 内存。该内存不能为 %s。
14:01:28.140 ERROR [LeviLamina] Parameter 0: 0x0
14:01:28.140 ERROR [LeviLamina] Parameter 1: 0xfffffffffffffffd

### To Reproduce

使用1.20.80.05(ProtocolVersion 671)+LeviLamina-0.12.4+935b0d8ee
加载插件后尝试重现

### Expected behavior

希望尽快修复（

### Screenshots

![image](https://github.com/engsr6982/ChainMiner3/assets/174303337/ad62a9bc-8c5b-47ed-9654-8d62b4bf9bc5)

### Platform

Windows11

### BDS Version

1.20.80.05(ProtocolVersion 671)

### LeviLamina Version

LeviLamina-0.12.4+935b0d8ee

### Version

0.3.2

**Comment by engsr6982** [comment]
根据堆栈信息来看，错误原因可能是
https://github.com/engsr6982/ChainMiner3/blob/v3/src/chainminer3/Plugin.cpp#L78

1. 请问服务器是否开启了“xbox验证”（online-mode）
2. 剩下的几次崩溃都是一样的原因吗？（不确定可以提供一下崩溃log吗）

**Comment by engsr6982** [comment]
无法复现，另外0.3.2版本的插件是使用LL 0.13.0的SDK编译，在旧版本可能出现未知异常
